import 'package:get/get.dart';

/// Register your texts here along with its translations
///
///
class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => <String, Map<String, String>>{
        'en': <String, String>{
          'auth.signInButton': 'Sign In',
          'auth.signUpButton': 'Sign Up',
          'auth.resetPasswordButton': 'Reset Password ',
          'auth.emailFormField': 'Email',
          'auth.passwordFormField': 'Password',
          'auth.nameFormField': 'Name',
          'auth.signInErrorTitle': 'Sign In Error',
          'auth.signInError': 'Login failed: email or password incorrect.',
          'auth.resetPasswordLabelButton': 'Forgot password?',
          'auth.signUpLabelButton': 'Create an Account',
          'auth.signUpErrorTitle': 'Sign Up Failed.',
          'auth.signUpError':
              'There was a problem signing up.  Please try again later.',
          'auth.signInLabelButton': 'Have an Account? Sign In.',
          'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
          'auth.resetPasswordNotice':
              'Check your email and follow the instructions to reset your password.',
          'auth.resetPasswordFailed': 'Password Reset Email Failed',
          'auth.signInonResetPasswordLabelButton': 'Sign In',
          'auth.updateUser': 'Update Profile',
          'auth.updateUserSuccessNoticeTitle': 'User Updated',
          'auth.updateUserSuccessNotice':
              'User information successfully updated.',
          'auth.updateUserFailNotice': 'Failed to update user',
          'auth.enterPassword': 'Enter your password',
          'auth.cancel': 'Cancel',
          'auth.submit': 'Submit',
          'auth.changePasswordLabelButton': 'Change Password',
          'auth.resetPasswordTitle': 'Reset Password',
          'auth.updateProfileTitle': 'Update Profile',
          'auth.wrongPasswordNoticeTitle': 'Login Failed',
          'auth.wrongPasswordNotice':
              'The password does not match our records.',
          'auth.unknownError': 'Unknown Error',
          'settings.title': 'Settings',
          'settings.language': 'Language',
          'settings.theme': 'Theme',
          'settings.signOut': 'Sign Out',
          'settings.dark': 'Dark',
          'settings.light': 'Light',
          'settings.system': 'System',
          'settings.updateProfile': 'Update Profile',
          'home.title': 'Home',
          'home.nameLabel': 'Name',
          'home.uidLabel': 'UID',
          'home.emailLabel': 'Email',
          'home.adminUserLabel': 'Admin User',
          'app.title': 'Flutter Starter Project',
          'validator.email': 'Please enter a valid email address.',
          'validator.password': 'Password must be at least 6 characters.',
          'validator.name': 'Please enter a name.',
          'validator.number': 'Please enter a number.',
          'validator.notEmpty': 'This is a required field.',
          'validator.amount':
              'Please enter a number i.e. 250 - no dollar symbol and no cents',
          'gender.female': 'Female',
          'gender.male': 'Male',
          'gender.undefined': 'Undefined',
        },
        'ja': <String, String>{
          'auth.signInButton': 'サインイン',
          'auth.signUpButton': 'サインアップ',
          'auth.resetPasswordButton': '送信パスワードリセット',
          'auth.emailFormField': 'Eメール',
          'auth.passwordFormField': 'パスワード',
          'auth.nameFormField': '名前',
          'auth.signInErrorTitle': 'エラーサインイン',
          'auth.signInError': 'ログインに失敗しました：電子メールまたはパスワードが正しくありません。',
          'auth.resetPasswordLabelButton': 'パスワードをお忘れですか？',
          'auth.signUpLabelButton': 'アカウントを作成する',
          'auth.signUpErrorTitle': 'サインアップは失敗しました。',
          'auth.signUpError': 'サインアップする問題が発生しました。後ほど再度お試しください。',
          'auth.signInLabelButton': 'アカウントを持っています？サインイン。',
          'auth.resetPasswordNoticeTitle': 'パスワードリセットのメール送信され',
          'auth.resetPasswordNotice':
              'あなたの電子メールをチェックして、あなたのパスワードをリセットするための指示に従ってください。',
          'auth.resetPasswordFailed': 'パスワードリセットのメールが失敗しました。',
          'auth.signInonResetPasswordLabelButton': 'サインイン',
          'auth.updateUser': 'プロフィールを更新',
          'auth.updateUserSuccessNoticeTitle': 'ユーザーの更新',
          'auth.updateUserSuccessNotice': 'ユーザー情報が正常に更新します。',
          'auth.updateUserFailNotice': '更新ユーザーに失敗しました。',
          'auth.enterPassword': 'パスワードを入力してください',
          'auth.cancel': 'キャンセル',
          'auth.submit': '参加する',
          'auth.changePasswordLabelButton': 'パスワードを変更する',
          'auth.resetPasswordTitle': 'パスワードを再設定する',
          'auth.updateProfileTitle': 'プロフィールを更新',
          'auth.wrongPasswordNoticeTitle': 'ログインに失敗しました',
          'auth.wrongPasswordNotice': 'パスワードは我々の記録と一致しません。',
          'auth.unknownError': '不明なエラー',
          'settings.title': '設定',
          'settings.language': '言語',
          'settings.theme': 'テーマ',
          'settings.signOut': 'サインアウト',
          'settings.dark': '闇',
          'settings.light': '光',
          'settings.system': 'システム',
          'settings.updateProfile': 'プロフィールを更新',
          'home.title': '家',
          'home.nameLabel': '名前',
          'home.uidLabel': 'UID',
          'home.emailLabel': 'Eメール',
          'home.adminUserLabel': '管理者ユーザー',
          'app.title': 'フラッタースタータープロジェクト',
          'validator.email': '有効なメールアドレスを入力してください。',
          'validator.password': 'パスワードは少なくとも6文字でなければなりません。',
          'validator.name': '名前を入力してください。',
          'validator.number': '番号を入力してください。',
          'validator.notEmpty': 'これは必要項目です。',
          'validator.amount': 'ノードル記号なしセント - すなわち、250番号を入力してください。',
          'gender.female': '女性',
          'gender.male': '男性',
          'gender.undefined': '回答しない',
        },
      };
}
